angle_fea_len: 80
batch_size: 12
bond_fea_len: 80
checkpoint_every: 20
embedding: false
epochs: 200
gamma: 0.5
h_fea_angle: 256
h_fea_edge: 256
learning_rate: 0.01
n_classification: 2
n_conv_edge: 2
neighbors: 12
num_workers: 4
pin_memory: true
rcut: 6
resume: false
search_delta: 20
search_type: global
step_size: 100
test_ratio: 0.0
train_ratio: 0.8
val_ratio: 0.2
