angle_fea_len: 80
batch_size: 4
bond_fea_len: 80
checkpoint_every: 20
embedding: false
epochs: 200
gamma: 0.5
h_fea_angle: 256
h_fea_edge: 256
learning_rate: 0.01
n_classification: 2
n_conv_edge: 1
neighbors: 12
num_workers: 4
pin_memory: true
rcut: 6
resume: false
search_delta: 5
search_type: local
step_size: 100
test_size: 0
train_size: 400
val_size: 40
